# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopAndSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('involved_person', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('operation', models.BooleanField(default=False)),
                ('operation_name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('age_range', models.TextField(blank=True, null=True)),
                ('self_defined_ethnicity', models.TextField(blank=True, null=True)),
                ('officer_defined_ethnicity', models.TextField(blank=True, null=True)),
                ('legislation', models.TextField(blank=True, null=True)),
                ('object_of_search', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('outcome_linked_to_object_of_search', models.TextField(blank=True, null=True)),
                ('removal_of_more_than_outer_clothing', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopAndSearchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('street_text', models.TextField()),
                ('stop_and_search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='stop_and_search.StopAndSearch')),
            ],
        ),
    ]
