# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_and_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopandsearchlocation',
            name='stop_and_search',
        ),
        migrations.AddField(
            model_name='stopandsearch',
            name='latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stopandsearch',
            name='longitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stopandsearch',
            name='street_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StopAndSearchLocation',
        ),
    ]
