# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stop_and_search', '0002_auto_20190526_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopandsearch',
            name='involved_person',
        ),
        migrations.RemoveField(
            model_name='stopandsearch',
            name='street_text',
        ),
    ]
